/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['NX/index.js']) {
  _$jscoverage['NX/index.js'] = [];
  _$jscoverage['NX/index.js'][11] = 0;
}
_$jscoverage['NX/index.js'][11]++;
require("./core.js");
_$jscoverage['NX/index.js'].source = ["/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */","","/*!"," * xFramework NX"," * Copyright(c) 2006-2011 Xenophy.CO.,LTD All rights Reserved."," * http://www.xenophy.com"," */","","// {{{ requires","","require('./core.js');","","// }}}","","/*"," * Local variables:"," * tab-width: 4"," * c-basic-offset: 4"," * c-hanging-comment-ender-p: nil"," * End:"," */"];
